# STUDENTS GENERATOR
STUDENTS_COUNT = 115

# COMMON
MAX_ITERATIONS = 10000
NUM_CLASSES = 4
HALL_OF_FAME_SIZE = 10

# SIMULATED ANNEALING
INITIAL_TEMP = 1000
COOLING_RATE = 0.999

# BEAM SEARCH
BEAM_WIDTH = 5

# EVOLUTIONARY ALGORITHM
POPULATION_SIZE = 100
GENERATIONS = 500
CX_PROB = 0.8  # Crossover probability
MUT_PROB = 0.2  # Mutation probability
